//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self help` (and `claude-self` with no subcommand) prints usage listing all subcommands [show, edit, lint, log, diff, default-restore, path, help] and exits 0. Unknown subcommands exit 2.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use predicates::str::contains;
use tempfile::TempDir;

const SUBS: [&str; 8] = ["show", "edit", "lint", "log", "diff", "default-restore", "path", "help"];

fn assert_usage_contains_subcommands(stdout: &str) {
    for sub in SUBS {
        assert!(stdout.contains(sub), "usage missing subcommand {sub}\nfull:\n{stdout}");
    }
}

#[test]
fn acceptance_ac6_help_prints_usage_listing_all_subcommands() {
    let tmp = TempDir::new().unwrap();
    let out = Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .arg("help")
        .assert()
        .success()
        .get_output()
        .clone();
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert_usage_contains_subcommands(&stdout);
}

#[test]
fn ac6_no_subcommand_prints_usage() {
    let tmp = TempDir::new().unwrap();
    let out = Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .assert()
        .success()
        .get_output()
        .clone();
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert_usage_contains_subcommands(&stdout);
}

#[test]
fn ac6_unknown_subcommand_exits_two() {
    let tmp = TempDir::new().unwrap();
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .arg("not-a-subcommand")
        .assert()
        .code(2)
        .stderr(contains("unknown subcommand"));
}
