//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self help` (and `claude-self` with no subcommand) prints usage listing all subcommands [show, edit, lint, log, diff, default-restore, path, help] and exits 0. Unknown subcommands exit 2.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac6() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC6 not yet implemented — see file header");
}
