//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self show` writes the live file's contents to stdout when present (exit 0); exits 2 with diagnostic on stderr when missing.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use predicates::str::contains;
use std::fs;
use tempfile::TempDir;

#[test]
fn acceptance_ac2_show_emits_file_contents_when_present() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    let body = "## Voice\n- terse\n";
    fs::write(&live, body).unwrap();
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &live)
        .arg("show")
        .assert()
        .success()
        .stdout(body);
}

#[test]
fn ac2_show_exits_2_with_diagnostic_when_missing() {
    let tmp = TempDir::new().unwrap();
    let missing = tmp.path().join("nope.md");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &missing)
        .arg("show")
        .assert()
        .code(2)
        .stderr(contains("not found"));
}
