//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self lint --quiet` suppresses all stdout/stderr output and preserves the same exit code as non-quiet mode.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use std::fs;
use tempfile::TempDir;

fn good_body() -> String {
    "# Header\n\
## Voice\n- Terse.\n\
## Values\n- Honest.\n\
## Defaults\n- Parallel.\n\
## Things I keep getting wrong\n- Over-narrating.\n\
## Aspirations\n- Be a collaborator.\n\
## Boundaries\n- No irreversible ops.\n\
## Changelog\n- 2026-05-23 (Claude): seed.\n"
        .to_string()
}

#[test]
fn acceptance_ac4_quiet_suppresses_output_on_pass() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    fs::write(&live, good_body()).unwrap();
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &live)
        .args(["lint", "--quiet"])
        .assert()
        .success()
        .stdout("")
        .stderr("");
}

#[test]
fn ac4_quiet_suppresses_output_on_fail() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    // Missing the Changelog section -> lint fails.
    let bad = good_body().replace("## Changelog\n- 2026-05-23 (Claude): seed.\n", "");
    fs::write(&live, bad).unwrap();
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &live)
        .args(["lint", "--quiet"])
        .assert()
        .code(1)
        .stdout("")
        .stderr("");
}

#[test]
fn ac4_quiet_preserves_missing_file_code_two() {
    let tmp = TempDir::new().unwrap();
    let missing = tmp.path().join("nope.md");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &missing)
        .args(["lint", "--quiet"])
        .assert()
        .code(2)
        .stdout("")
        .stderr("");
}
