//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self lint` enforces the four lint rules: (a) exactly the seven canonical section headers in order [Voice, Values, Defaults, Things I keep getting wrong, Aspirations, Boundaries, Changelog], (b) total length <= 200 lines, (c) Aspirations section has at least one non-empty bullet, (d) no duplicate bullets within any section. Exit 0 on pass, 1 on any rule violation.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use std::fs;
use std::path::Path;
use tempfile::TempDir;

fn good_body() -> String {
    "# Header\n\
## Voice\n- Terse.\n\
## Values\n- Honest.\n\
## Defaults\n- Parallel.\n\
## Things I keep getting wrong\n- Over-narrating.\n\
## Aspirations\n- Be a collaborator.\n\
## Boundaries\n- No irreversible ops.\n\
## Changelog\n- 2026-05-23 (Claude): seed.\n"
        .to_string()
}

fn run_lint(tmp: &Path, live: &Path) -> assert_cmd::assert::Assert {
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp)
        .env("CLAUDE_SELF_FILE", live)
        .arg("lint")
        .assert()
}

#[test]
fn acceptance_ac3_good_file_lints_clean_exit_zero() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    fs::write(&live, good_body()).unwrap();
    run_lint(tmp.path(), &live).success();
}

#[test]
fn ac3_section_mismatch_exits_one() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    // Missing the Changelog section.
    let bad = good_body().replace("## Changelog\n- 2026-05-23 (Claude): seed.\n", "");
    fs::write(&live, bad).unwrap();
    run_lint(tmp.path(), &live).code(1);
}

#[test]
fn ac3_over_200_lines_exits_one() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    let mut bad = good_body();
    // Pad inside the Voice section past the 200-line cap.
    let mut pad = String::new();
    for i in 0..220 {
        pad.push_str(&format!("- pad{i}\n"));
    }
    bad = bad.replacen("## Voice\n- Terse.\n", &format!("## Voice\n- Terse.\n{pad}"), 1);
    fs::write(&live, bad).unwrap();
    run_lint(tmp.path(), &live).code(1);
}

#[test]
fn ac3_empty_aspirations_exits_one() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    let bad = good_body().replace("- Be a collaborator.\n", "");
    fs::write(&live, bad).unwrap();
    run_lint(tmp.path(), &live).code(1);
}

#[test]
fn ac3_duplicate_bullets_exits_one() {
    let tmp = TempDir::new().unwrap();
    let live = tmp.path().join("self.md");
    let bad = good_body().replace("## Values\n- Honest.\n", "## Values\n- Honest.\n- Honest.\n");
    fs::write(&live, bad).unwrap();
    run_lint(tmp.path(), &live).code(1);
}
