//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self path` prints the resolved live-file path (default `$HOME/.claude/CLAUDE_SELF.md`, overridable via `CLAUDE_SELF_FILE`) to stdout and exits 0.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1_path_default_resolves_under_home() {
    let tmp = TempDir::new().unwrap();
    let expected = tmp.path().join(".claude").join("CLAUDE_SELF.md");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .arg("path")
        .assert()
        .success()
        .stdout(format!("{}\n", expected.display()));
}

#[test]
fn ac1_path_env_override_wins() {
    let tmp = TempDir::new().unwrap();
    let explicit = tmp.path().join("custom-self.md");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_SELF_FILE", &explicit)
        .arg("path")
        .assert()
        .success()
        .stdout(format!("{}\n", explicit.display()));
}
