//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: claude-self (cli)
//! AC description: `claude-self log` and `claude-self diff [REF]` shell out to git in the dotfiles repo (path overridable via `CLAUDE_DOTFILES`) restricted to the live file's tracked path; when the dotfiles repo is missing, exit 2 with a clear diagnostic. Implementation may delegate to `git`; the test asserts the diagnostic path when no repo exists.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use assert_cmd::Command;
use predicates::str::contains;
use tempfile::TempDir;

#[test]
fn acceptance_ac7_log_missing_dotfiles_repo_exits_two_with_diagnostic() {
    let tmp = TempDir::new().unwrap();
    let absent_dotfiles = tmp.path().join("no-dotfiles");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_DOTFILES", &absent_dotfiles)
        .arg("log")
        .assert()
        .code(2)
        .stderr(contains("dotfiles repo not found"));
}

#[test]
fn ac7_diff_missing_dotfiles_repo_exits_two_with_diagnostic() {
    let tmp = TempDir::new().unwrap();
    let absent_dotfiles = tmp.path().join("no-dotfiles");
    Command::cargo_bin("claude-self")
        .unwrap()
        .env_clear()
        .env("HOME", tmp.path())
        .env("CLAUDE_DOTFILES", &absent_dotfiles)
        .arg("diff")
        .assert()
        .code(2)
        .stderr(contains("dotfiles repo not found"));
}
